### ISSUE TITLE
Increase RAM for tika

### ISSUE THREAD

**Issue by jone** [4teamwork/ftw-buildouts#25]
The tika server seems to have not enough RAM by default.

Todo:
- Declare a buildout variable in [production.cfg](https://github.com/4teamwork/ftw-buildouts/blob/master/production.cfg#L36), e.g. `tika-memory`
- Inlcude variable in java arguments of [tika-jaxrs-server.cfg](https://github.com/4teamwork/ftw-buildouts/blob/master/tika-jaxrs-server.cfg#L42)

Possible problem:
Memmon may restart the process when the consumed RAM is more than [1200 MB (default)](https://github.com/4teamwork/ftw-buildouts/blob/master/production.cfg#L32)

@lukasgraf is this the right approach? How much memory should be the default?

**Comment by lukasgraf** [comment]
@jone yes, this should work. I've already done this in [`opengever.zug:tika-buildout`](https://github.com/4teamwork/opengever.zug/blob/tika-buildout/buildout.cfg#L40) in a hard-coded way.

**Important**: Make sure you use a `Memmon` that includes https://github.com/Supervisor/superlance/pull/44 and enable cumulative RSS with the `-c` flag ([example](https://github.com/4teamwork/opengever.zug/blob/tika-buildout/buildout.cfg#L18)) - otherwise `Memmon` will watch the ~12kb RSS memory of the `bin/tika-server` wrapper shell script :grinning:
